export default {
  nav: { home: 'الرئيسية', brands: 'العلامات', verify: 'التحقق', mypage: 'صفحتي', atelier: 'أتيليه', admin: 'الإدارة', api: 'Open API', login: 'تسجيل الدخول', logout: 'تسجيل الخروج' },
  hero: { tag: 'منصة شهادات K-BEAUTY الرقمية', title: 'BEAUTY IDENTITY\nAWARD', sub: 'احصل على شهادة W3C VC لأصول K-Beauty\nواحفظها إلى الأبد على بيتكوين', cta_primary: 'التقدم للحصول على شهادة', cta_secondary: 'البحث في الشهادات', stats: { vcs: 'VCs صادرة', inscribed: 'مسجلة في بيتكوين', brands: 'علامات معتمدة', block: 'أحدث كتلة' } },
  btc: { title: 'تسجيل بيتكوين اليومي', subtitle: 'في كل منتصف ليل KST يتم تجميع جميع VCs في Merkle Tree وتسجيلها بشكل دائم على بيتكوين', status: { pending: 'في الانتظار', submitted: 'تم إرسال OTS', confirmed: 'تم التأكيد' }, next_batch: 'الدفعة التالية خلال' },
  verify: { title: 'البحث والتحقق من الشهادات', placeholder: 'VC ID · تجزئة SHA-256 · BTC TX · علامة · منتج', btn: 'تحقق', loading: 'جارٍ التحقق...', status: { valid: 'شهادة صالحة', revoked: 'شهادة ملغاة' }, inscribed: 'مسجلة في بيتكوين', pending: 'في انتظار تسجيل بيتكوين', ots_submitted: 'تم إرسال OTS · في انتظار تأكيد الكتلة', not_found: 'الشهادة غير موجودة', merkle_title: 'مسار إثبات Merkle', batch_date: 'تاريخ الدفعة', leaf_index: 'الموضع في الدفعة' },
  brand: { assets: 'الأصول المعتمدة', sbt: 'SBT', nft: 'NFT', verified: 'معتمد رسمياً من Kei', qr_download: 'تحميل QR', short_url: 'نسخ الرابط القصير' },
  auth: { title: 'تسجيل الدخول award.bi', sub: 'احصل على رمز مكون من 6 أرقام عبر البريد الإلكتروني', email_label: 'البريد الإلكتروني', email_placeholder: 'your@email.com', send_otp: 'استلام الرمز ←', otp_title: 'أدخل رمز التحقق', otp_sub: 'أدخل الرمز المكون من 6 أرقام المُرسل إلى بريدك', verify_btn: 'إتمام تسجيل الدخول', resend: 'إعادة إرسال الرمز', back: '← إعادة إدخال البريد الإلكتروني', err_email: 'الرجاء إدخال بريد إلكتروني صالح', err_otp: 'الرمز غير صحيح أو منتهي الصلاحية.\nالرجاء طلب رمز جديد.', err_server: 'خطأ في الخادم. حاول مرة أخرى لاحقاً.', err_code: 'الرجاء إدخال الأرقام الستة كاملة' },
  mypage: { title: 'صفحتي', points: 'نقاط ssum', my_certs: 'شهاداتي', issue: 'تسجيل أصل', market: 'سوق NFT', history: 'سجل النشاط', no_certs: 'لا توجد شهادات بعد', did: 'W3C DID' },
  issue: { title: 'تسجيل SBT / NFT', step1: 'نوع الأصل', step2: 'رفع الملف', step3: 'بيانات وصفية', step4: 'إرسال', sbt_desc: 'غير قابل للنقل — يقفل هوية العلامة', nft_desc: 'قابل للنقل — يمكن عرضه في السوق', submit_btn: 'إرسال إلى Atelier' },
  market: { title: 'سوق NFT', filter_all: 'الكل', buy_btn: 'شراء بالنقاط', list_btn: 'عرض في السوق', price: 'السعر (نقاط)', seller: 'البائع' },
  footer: { copy: '© 2026 award.bi · Powered by kei.bio · تسجيل دائم على بيتكوين', links: { verify: 'التحقق', api: 'Open API', brand: 'العلامات', atelier: 'أتيليه' } },
}
