export default {
  nav: { home: 'Startseite', brands: 'Marken', verify: 'Verifizieren', mypage: 'Mein Bereich', atelier: 'Atelier', admin: 'Admin', api: 'Open API', login: 'Anmelden', logout: 'Abmelden' },
  hero: { tag: 'K-BEAUTY DIGITALE ZERTIFIZIERUNGSPLATTFORM', title: 'BEAUTY IDENTITY\nAWARD', sub: 'K-Beauty Assets mit W3C VC authentifizieren\nund dauerhaft auf Bitcoin einschreiben', cta_primary: 'Zertifizierung beantragen', cta_secondary: 'Zertifikate suchen', stats: { vcs: 'Ausgestellte VCs', inscribed: 'Bitcoin eingeschrieben', brands: 'Zertifizierte Marken', block: 'Letzter Block' } },
  btc: { title: 'Tägliche Bitcoin-Inschrift', subtitle: 'Jeden Mitternacht KST werden alle VCs in einem Merkle Tree gebündelt und dauerhaft auf Bitcoin aufgezeichnet', status: { pending: 'Ausstehend', submitted: 'OTS eingereicht', confirmed: 'Bestätigt' }, next_batch: 'Nächster Batch in' },
  verify: { title: 'Zertifikate suchen & verifizieren', placeholder: 'VC ID · SHA-256 Hash · BTC TX · Marke · Produkt', btn: 'Verifizieren', loading: 'Verifizierung...', status: { valid: 'Gültiges Zertifikat', revoked: 'Widerrufenes Zertifikat' }, inscribed: 'Auf Bitcoin eingeschrieben', pending: 'Warte auf Bitcoin-Inschrift', ots_submitted: 'OTS eingereicht · Warte auf Blockbestätigung', not_found: 'Zertifikat nicht gefunden', merkle_title: 'Merkle-Beweispfad', batch_date: 'Batch-Datum', leaf_index: 'Position im Batch' },
  brand: { assets: 'Zertifizierte Assets', sbt: 'SBT', nft: 'NFT', verified: 'Kei offiziell zertifiziert', qr_download: 'QR herunterladen', short_url: 'Kurz-URL kopieren' },
  auth: { title: 'award.bi Anmeldung', sub: 'Erhalten Sie einen 6-stelligen Code per E-Mail zum Anmelden', email_label: 'E-Mail', email_placeholder: 'your@email.com', send_otp: 'Code erhalten →', otp_title: 'Code eingeben', otp_sub: 'Geben Sie den 6-stelligen Code ein, der an Ihre E-Mail gesendet wurde', verify_btn: 'Anmeldung abschließen', resend: 'Code erneut senden', back: '← E-Mail erneut eingeben', err_email: 'Bitte geben Sie eine gültige E-Mail ein', err_otp: 'Code ungültig oder abgelaufen.\nBitte neuen Code anfordern.', err_server: 'Serverfehler. Bitte versuchen Sie es später erneut.', err_code: 'Bitte alle 6 Ziffern eingeben' },
  mypage: { title: 'Mein Bereich', points: 'ssum Punkte', my_certs: 'Meine Zertifikate', issue: 'Asset registrieren', market: 'NFT-Markt', history: 'Aktivitätsverlauf', no_certs: 'Noch keine Zertifikate', did: 'W3C DID' },
  issue: { title: 'SBT / NFT registrieren', step1: 'Asset-Typ', step2: 'Datei hochladen', step3: 'Metadaten', step4: 'Einreichen', sbt_desc: 'Nicht übertragbar — sperrt Markenidentität', nft_desc: 'Übertragbar — kann auf dem Markt gelistet werden', submit_btn: 'Ans Atelier einreichen' },
  market: { title: 'NFT-Markt', filter_all: 'Alle', buy_btn: 'Mit Punkten kaufen', list_btn: 'Auf dem Markt listen', price: 'Preis (Punkte)', seller: 'Verkäufer' },
  footer: { copy: '© 2026 award.bi · Powered by kei.bio · Permanente Bitcoin-Inschrift', links: { verify: 'Verifizieren', api: 'Open API', brand: 'Marken', atelier: 'Atelier' } },
}
