export default {
  nav: { home: 'Inicio', brands: 'Marcas', verify: 'Verificar', mypage: 'Mi espacio', atelier: 'Atelier', admin: 'Admin', api: 'Open API', login: 'Iniciar sesión', logout: 'Cerrar sesión' },
  hero: { tag: 'PLATAFORMA DE CERTIFICACIÓN DIGITAL K-BEAUTY', title: 'BEAUTY IDENTITY\nAWARD', sub: 'Autentifica activos K-Beauty con W3C VC\ne inscríbelos permanentemente en Bitcoin', cta_primary: 'Solicitar certificación', cta_secondary: 'Buscar certificados', stats: { vcs: 'VCs emitidos', inscribed: 'Inscritos en Bitcoin', brands: 'Marcas certificadas', block: 'Último bloque' } },
  btc: { title: 'Inscripción diaria en Bitcoin', subtitle: 'Cada medianoche KST, todos los VCs se agrupan en un Merkle Tree y se registran permanentemente en Bitcoin', status: { pending: 'Pendiente', submitted: 'OTS enviado', confirmed: 'Confirmado' }, next_batch: 'Próximo lote en' },
  verify: { title: 'Buscar y verificar certificados', placeholder: 'VC ID · Hash SHA-256 · BTC TX · Marca · Producto', btn: 'Verificar', loading: 'Verificando...', status: { valid: 'Certificado válido', revoked: 'Certificado revocado' }, inscribed: 'Inscrito en Bitcoin', pending: 'En espera de inscripción Bitcoin', ots_submitted: 'OTS enviado · Esperando confirmación de bloque', not_found: 'Certificado no encontrado', merkle_title: 'Ruta de prueba Merkle', batch_date: 'Fecha del lote', leaf_index: 'Posición en el lote' },
  brand: { assets: 'Activos certificados', sbt: 'SBT', nft: 'NFT', verified: 'Kei certificado oficial', qr_download: 'Descargar QR', short_url: 'Copiar URL corta' },
  auth: { title: 'Iniciar sesión en award.bi', sub: 'Recibe un código de 6 dígitos por email para iniciar sesión', email_label: 'Email', email_placeholder: 'your@email.com', send_otp: 'Recibir código →', otp_title: 'Ingresar código', otp_sub: 'Ingresa el código de 6 dígitos enviado a tu email', verify_btn: 'Completar inicio de sesión', resend: 'Reenviar código', back: '← Volver a ingresar email', err_email: 'Ingresa un email válido', err_otp: 'Código inválido o expirado.\nSolicita un nuevo código.', err_server: 'Error del servidor. Inténtalo más tarde.', err_code: 'Ingresa los 6 dígitos completos' },
  mypage: { title: 'Mi espacio', points: 'Puntos ssum', my_certs: 'Mis certificados', issue: 'Registrar activo', market: 'Mercado NFT', history: 'Historial de actividad', no_certs: 'Aún no hay certificados', did: 'W3C DID' },
  issue: { title: 'Registrar SBT / NFT', step1: 'Tipo de activo', step2: 'Subir archivo', step3: 'Metadatos', step4: 'Enviar', sbt_desc: 'No transferible — bloquea identidad de marca', nft_desc: 'Transferible — puede listarse en el mercado', submit_btn: 'Enviar al Atelier' },
  market: { title: 'Mercado NFT', filter_all: 'Todos', buy_btn: 'Comprar con puntos', list_btn: 'Listar en mercado', price: 'Precio (Puntos)', seller: 'Vendedor' },
  footer: { copy: '© 2026 award.bi · Powered by kei.bio · Inscripción permanente en Bitcoin', links: { verify: 'Verificar', api: 'Open API', brand: 'Marcas', atelier: 'Atelier' } },
}
