export default {
  nav: { home: 'Accueil', brands: 'Marques', verify: 'Vérifier', mypage: 'Mon espace', atelier: 'Atelier', admin: 'Admin', api: 'Open API', login: 'Connexion', logout: 'Déconnexion' },
  hero: { tag: 'PLATEFORME DE CERTIFICATION NUMÉRIQUE K-BEAUTY', title: 'BEAUTY IDENTITY\nAWARD', sub: 'Authentifiez les actifs K-Beauty avec W3C VC\net inscrivez-les définitivement sur Bitcoin', cta_primary: 'Demander une certification', cta_secondary: 'Rechercher des certificats', stats: { vcs: 'VC émis', inscribed: 'Inscrit sur Bitcoin', brands: 'Marques certifiées', block: 'Dernier bloc' } },
  btc: { title: 'Inscription Bitcoin quotidienne', subtitle: 'Chaque minuit KST, tous les VC sont regroupés dans un Merkle Tree et enregistrés définitivement sur Bitcoin', status: { pending: 'En attente', submitted: 'OTS soumis', confirmed: 'Confirmé' }, next_batch: 'Prochain lot dans' },
  verify: { title: 'Rechercher & Vérifier les certificats', placeholder: 'VC ID · Hash SHA-256 · BTC TX · Marque · Produit', btn: 'Vérifier', loading: 'Vérification...', status: { valid: 'Certificat valide', revoked: 'Certificat révoqué' }, inscribed: 'Inscrit sur Bitcoin', pending: 'En attente d\'inscription Bitcoin', ots_submitted: 'OTS soumis · En attente de confirmation de bloc', not_found: 'Certificat introuvable', merkle_title: 'Chemin de preuve Merkle', batch_date: 'Date du lot', leaf_index: 'Position dans le lot' },
  brand: { assets: 'Actifs certifiés', sbt: 'SBT', nft: 'NFT', verified: 'Kei certifié officiel', qr_download: 'Télécharger QR', short_url: 'Copier l\'URL courte' },
  auth: { title: 'Connexion award.bi', sub: 'Recevez un code à 6 chiffres par email pour vous connecter', email_label: 'Email', email_placeholder: 'your@email.com', send_otp: 'Recevoir le code →', otp_title: 'Entrer le code', otp_sub: 'Entrez le code à 6 chiffres envoyé à votre email', verify_btn: 'Connexion terminée', resend: 'Renvoyer le code', back: '← Saisir à nouveau l\'email', err_email: 'Veuillez saisir un email valide', err_otp: 'Code invalide ou expiré.\nVeuillez demander un nouveau code.', err_server: 'Erreur serveur. Réessayez plus tard.', err_code: 'Veuillez saisir les 6 chiffres' },
  mypage: { title: 'Mon espace', points: 'Points ssum', my_certs: 'Mes certificats', issue: 'Enregistrer un actif', market: 'Marché NFT', history: 'Historique d\'activité', no_certs: 'Aucun certificat encore', did: 'W3C DID' },
  issue: { title: 'Enregistrer SBT / NFT', step1: 'Type d\'actif', step2: 'Télécharger fichier', step3: 'Métadonnées', step4: 'Soumettre', sbt_desc: 'Non transférable — verrouille l\'identité de marque', nft_desc: 'Transférable — peut être listé sur le marché', submit_btn: 'Soumettre à l\'Atelier' },
  market: { title: 'Marché NFT', filter_all: 'Tout', buy_btn: 'Acheter avec des points', list_btn: 'Lister sur le marché', price: 'Prix (Points)', seller: 'Vendeur' },
  footer: { copy: '© 2026 award.bi · Powered by kei.bio · Inscription permanente Bitcoin', links: { verify: 'Vérifier', api: 'Open API', brand: 'Marques', atelier: 'Atelier' } },
}
