export default {
  nav: { home: 'Beranda', brands: 'Merek', verify: 'Verifikasi', mypage: 'Halaman Saya', atelier: 'Atelier', admin: 'Admin', api: 'Open API', login: 'Masuk', logout: 'Keluar' },
  hero: { tag: 'PLATFORM SERTIFIKASI DIGITAL K-BEAUTY', title: 'BEAUTY IDENTITY\nAWARD', sub: 'Otentikasi aset K-Beauty dengan W3C VC\ndan catat secara permanen di Bitcoin', cta_primary: 'Daftar Sertifikasi', cta_secondary: 'Cari Sertifikat', stats: { vcs: 'VC Diterbitkan', inscribed: 'Terukir Bitcoin', brands: 'Merek Bersertifikat', block: 'Blok Terbaru' } },
  btc: { title: 'Ukiran Bitcoin Harian', subtitle: 'Setiap tengah malam KST, semua VC digabungkan dalam Merkle Tree dan dicatat secara permanen di Bitcoin', status: { pending: 'Menunggu', submitted: 'OTS Dikirim', confirmed: 'Dikonfirmasi' }, next_batch: 'Ke batch berikutnya' },
  verify: { title: 'Cari & Verifikasi Sertifikat', placeholder: 'VC ID · Hash SHA-256 · BTC TX · Merek · Produk', btn: 'Verifikasi', loading: 'Memverifikasi...', status: { valid: 'Sertifikat Valid', revoked: 'Sertifikat Dicabut' }, inscribed: 'Terukir di Bitcoin', pending: 'Menunggu Ukiran Bitcoin', ots_submitted: 'OTS Terkirim · Menunggu Konfirmasi Blok', not_found: 'Sertifikat tidak ditemukan', merkle_title: 'Jalur Bukti Merkle', batch_date: 'Tanggal Batch', leaf_index: 'Posisi dalam Batch' },
  brand: { assets: 'Aset Bersertifikat', sbt: 'SBT', nft: 'NFT', verified: 'Kei Bersertifikat Resmi', qr_download: 'Unduh QR', short_url: 'Salin URL Pendek' },
  auth: { title: 'Masuk award.bi', sub: 'Terima kode 6 digit melalui email untuk masuk', email_label: 'Email', email_placeholder: 'your@email.com', send_otp: 'Kirim Kode →', otp_title: 'Masukkan Kode', otp_sub: 'Masukkan kode 6 digit yang dikirim ke email Anda', verify_btn: 'Selesaikan Login', resend: 'Kirim Ulang Kode', back: '← Masukkan Email Lagi', err_email: 'Masukkan email yang valid', err_otp: 'Kode tidak valid atau kedaluwarsa.\nMinta kode baru.', err_server: 'Kesalahan server. Coba lagi nanti.', err_code: 'Masukkan semua 6 digit' },
  mypage: { title: 'Halaman Saya', points: 'Poin ssum', my_certs: 'Sertifikat Saya', issue: 'Daftarkan Aset', market: 'Pasar NFT', history: 'Riwayat Aktivitas', no_certs: 'Belum ada sertifikat', did: 'W3C DID' },
  issue: { title: 'Daftarkan SBT / NFT', step1: 'Jenis Aset', step2: 'Unggah File', step3: 'Metadata', step4: 'Kirim', sbt_desc: 'Tidak dapat dipindahtangankan — mengunci identitas merek', nft_desc: 'Dapat dipindahtangankan — bisa didaftarkan di pasar', submit_btn: 'Kirim ke Atelier' },
  market: { title: 'Pasar NFT', filter_all: 'Semua', buy_btn: 'Beli dengan Poin', list_btn: 'Daftar di Pasar', price: 'Harga (Poin)', seller: 'Penjual' },
  footer: { copy: '© 2026 award.bi · Powered by kei.bio · Ukiran Permanen Bitcoin', links: { verify: 'Verifikasi', api: 'Open API', brand: 'Merek', atelier: 'Atelier' } },
}
