export default {
  nav: { home: 'Início', brands: 'Marcas', verify: 'Verificar', mypage: 'Minha página', atelier: 'Atelier', admin: 'Admin', api: 'Open API', login: 'Entrar', logout: 'Sair' },
  hero: { tag: 'PLATAFORMA DE CERTIFICAÇÃO DIGITAL K-BEAUTY', title: 'BEAUTY IDENTITY\nAWARD', sub: 'Autentique ativos K-Beauty com W3C VC\ne inscreva-os permanentemente no Bitcoin', cta_primary: 'Solicitar certificação', cta_secondary: 'Buscar certificados', stats: { vcs: 'VCs emitidos', inscribed: 'Inscritos no Bitcoin', brands: 'Marcas certificadas', block: 'Último bloco' } },
  btc: { title: 'Inscrição diária no Bitcoin', subtitle: 'Toda meia-noite KST, todos os VCs são agrupados em uma Merkle Tree e registrados permanentemente no Bitcoin', status: { pending: 'Pendente', submitted: 'OTS enviado', confirmed: 'Confirmado' }, next_batch: 'Próximo lote em' },
  verify: { title: 'Buscar e verificar certificados', placeholder: 'VC ID · Hash SHA-256 · BTC TX · Marca · Produto', btn: 'Verificar', loading: 'Verificando...', status: { valid: 'Certificado válido', revoked: 'Certificado revogado' }, inscribed: 'Inscrito no Bitcoin', pending: 'Aguardando inscrição no Bitcoin', ots_submitted: 'OTS enviado · Aguardando confirmação de bloco', not_found: 'Certificado não encontrado', merkle_title: 'Caminho de prova Merkle', batch_date: 'Data do lote', leaf_index: 'Posição no lote' },
  brand: { assets: 'Ativos certificados', sbt: 'SBT', nft: 'NFT', verified: 'Kei certificado oficial', qr_download: 'Baixar QR', short_url: 'Copiar URL curta' },
  auth: { title: 'Entrar no award.bi', sub: 'Receba um código de 6 dígitos por email para entrar', email_label: 'Email', email_placeholder: 'your@email.com', send_otp: 'Receber código →', otp_title: 'Inserir código', otp_sub: 'Insira o código de 6 dígitos enviado ao seu email', verify_btn: 'Concluir login', resend: 'Reenviar código', back: '← Inserir email novamente', err_email: 'Insira um email válido', err_otp: 'Código inválido ou expirado.\nSolicite um novo código.', err_server: 'Erro no servidor. Tente novamente mais tarde.', err_code: 'Insira todos os 6 dígitos' },
  mypage: { title: 'Minha página', points: 'Pontos ssum', my_certs: 'Meus certificados', issue: 'Registrar ativo', market: 'Mercado NFT', history: 'Histórico de atividades', no_certs: 'Ainda não há certificados', did: 'W3C DID' },
  issue: { title: 'Registrar SBT / NFT', step1: 'Tipo de ativo', step2: 'Upload de arquivo', step3: 'Metadados', step4: 'Enviar', sbt_desc: 'Não transferível — bloqueia identidade da marca', nft_desc: 'Transferível — pode ser listado no mercado', submit_btn: 'Enviar ao Atelier' },
  market: { title: 'Mercado NFT', filter_all: 'Todos', buy_btn: 'Comprar com pontos', list_btn: 'Listar no mercado', price: 'Preço (Pontos)', seller: 'Vendedor' },
  footer: { copy: '© 2026 award.bi · Powered by kei.bio · Inscrição permanente no Bitcoin', links: { verify: 'Verificar', api: 'Open API', brand: 'Marcas', atelier: 'Atelier' } },
}
