export default {
  nav: { home: 'หน้าหลัก', brands: 'แบรนด์', verify: 'ยืนยัน', mypage: 'ของฉัน', atelier: 'Atelier', admin: 'ผู้ดูแล', api: 'Open API', login: 'เข้าสู่ระบบ', logout: 'ออกจากระบบ' },
  hero: { tag: 'แพลตฟอร์มรับรองดิจิทัล K-BEAUTY', title: 'BEAUTY IDENTITY\nAWARD', sub: 'รับรองสินทรัพย์ K-Beauty ด้วย W3C VC\nและบันทึกถาวรบน Bitcoin', cta_primary: 'สมัครรับรอง', cta_secondary: 'ค้นหาใบรับรอง', stats: { vcs: 'VC ที่ออก', inscribed: 'บันทึก Bitcoin', brands: 'แบรนด์ที่รับรอง', block: 'บล็อกล่าสุด' } },
  btc: { title: 'บันทึก Bitcoin รายวัน', subtitle: 'ทุกเที่ยงคืน KST VC ทั้งหมดถูกรวมใน Merkle Tree และบันทึกถาวรบน Bitcoin', status: { pending: 'รอดำเนินการ', submitted: 'ส่ง OTS แล้ว', confirmed: 'ยืนยันแล้ว' }, next_batch: 'ถึงชุดถัดไป' },
  verify: { title: 'ค้นหา & ยืนยันใบรับรอง', placeholder: 'VC ID · แฮช SHA-256 · BTC TX · แบรนด์ · ผลิตภัณฑ์', btn: 'ยืนยัน', loading: 'กำลังยืนยัน...', status: { valid: 'ใบรับรองที่ถูกต้อง', revoked: 'ใบรับรองที่ถูกเพิกถอน' }, inscribed: 'บันทึก Bitcoin แล้ว', pending: 'รอบันทึก Bitcoin', ots_submitted: 'ส่ง OTS แล้ว · รอยืนยันบล็อก', not_found: 'ไม่พบใบรับรอง', merkle_title: 'เส้นทาง Merkle', batch_date: 'วันที่ชุด', leaf_index: 'ลำดับในชุด' },
  brand: { assets: 'สินทรัพย์ที่รับรอง', sbt: 'SBT', nft: 'NFT', verified: 'Kei รับรองอย่างเป็นทางการ', qr_download: 'ดาวน์โหลด QR', short_url: 'คัดลอก URL สั้น' },
  auth: { title: 'เข้าสู่ระบบ award.bi', sub: 'รับรหัส 6 หลักทางอีเมลเพื่อเข้าสู่ระบบ', email_label: 'อีเมล', email_placeholder: 'your@email.com', send_otp: 'รับรหัส →', otp_title: 'ป้อนรหัสยืนยัน', otp_sub: 'ป้อนรหัส 6 หลักที่ส่งไปยังอีเมลของคุณ', verify_btn: 'เข้าสู่ระบบสำเร็จ', resend: 'ส่งรหัสอีกครั้ง', back: '← ป้อนอีเมลอีกครั้ง', err_email: 'กรุณาป้อนอีเมลที่ถูกต้อง', err_otp: 'รหัสไม่ถูกต้องหรือหมดอายุ\nกรุณาส่งรหัสใหม่', err_server: 'เกิดข้อผิดพลาดของเซิร์ฟเวอร์ กรุณาลองใหม่', err_code: 'กรุณาป้อนครบ 6 หลัก' },
  mypage: { title: 'หน้าของฉัน', points: 'คะแนน ssum', my_certs: 'ใบรับรองของฉัน', issue: 'ลงทะเบียนสินทรัพย์', market: 'ตลาด NFT', history: 'ประวัติกิจกรรม', no_certs: 'ยังไม่มีใบรับรอง', did: 'W3C DID' },
  issue: { title: 'ลงทะเบียน SBT / NFT', step1: 'ประเภทสินทรัพย์', step2: 'อัปโหลดไฟล์', step3: 'ข้อมูลเมตา', step4: 'ส่ง', sbt_desc: 'ไม่สามารถโอนได้ — ล็อคตัวตนแบรนด์', nft_desc: 'โอนได้ — ลงประกาศในตลาดได้', submit_btn: 'ส่งให้ Atelier ตรวจสอบ' },
  market: { title: 'ตลาด NFT', filter_all: 'ทั้งหมด', buy_btn: 'ซื้อด้วยคะแนน', list_btn: 'ลงประกาศในตลาด', price: 'ราคา (คะแนน)', seller: 'ผู้ขาย' },
  footer: { copy: '© 2026 award.bi · Powered by kei.bio · Bitcoin บันทึกถาวร', links: { verify: 'ยืนยัน', api: 'Open API', brand: 'แบรนด์', atelier: 'Atelier' } },
}
