export default {
  nav: { home: 'Trang chủ', brands: 'Thương hiệu', verify: 'Xác minh', mypage: 'Trang của tôi', atelier: 'Atelier', admin: 'Quản trị', api: 'Open API', login: 'Đăng nhập', logout: 'Đăng xuất' },
  hero: { tag: 'NỀN TẢNG CHỨNG NHẬN KỸ THUẬT SỐ K-BEAUTY', title: 'BEAUTY IDENTITY\nAWARD', sub: 'Xác thực tài sản K-Beauty bằng W3C VC\nvà ghi vĩnh viễn lên Bitcoin', cta_primary: 'Đăng ký chứng nhận', cta_secondary: 'Tìm kiếm chứng chỉ', stats: { vcs: 'VC đã phát hành', inscribed: 'Bitcoin đã ghi', brands: 'Thương hiệu được chứng nhận', block: 'Khối mới nhất' } },
  btc: { title: 'Ghi Bitcoin hàng ngày', subtitle: 'Mỗi nửa đêm KST, tất cả VC được kết hợp thành Merkle Tree và ghi vĩnh viễn lên Bitcoin', status: { pending: 'Chờ xử lý', submitted: 'Đã gửi OTS', confirmed: 'Đã xác nhận' }, next_batch: 'Đến đợt tiếp theo' },
  verify: { title: 'Tìm kiếm & Xác minh Chứng chỉ', placeholder: 'VC ID · Hash SHA-256 · BTC TX · Thương hiệu · Sản phẩm', btn: 'Xác minh', loading: 'Đang xác minh...', status: { valid: 'Chứng chỉ hợp lệ', revoked: 'Chứng chỉ đã thu hồi' }, inscribed: 'Đã ghi Bitcoin', pending: 'Chờ ghi Bitcoin', ots_submitted: 'Đã gửi OTS · Chờ xác nhận khối', not_found: 'Không tìm thấy chứng chỉ', merkle_title: 'Đường dẫn Merkle', batch_date: 'Ngày đợt', leaf_index: 'Vị trí trong đợt' },
  brand: { assets: 'Tài sản được chứng nhận', sbt: 'SBT', nft: 'NFT', verified: 'Kei Chứng nhận chính thức', qr_download: 'Tải QR', short_url: 'Sao chép URL ngắn' },
  auth: { title: 'Đăng nhập award.bi', sub: 'Nhận mã 6 chữ số qua email để đăng nhập', email_label: 'Email', email_placeholder: 'your@email.com', send_otp: 'Nhận mã →', otp_title: 'Nhập mã xác minh', otp_sub: 'Nhập mã 6 chữ số được gửi đến email của bạn', verify_btn: 'Hoàn tất đăng nhập', resend: 'Gửi lại mã', back: '← Nhập lại email', err_email: 'Vui lòng nhập email hợp lệ', err_otp: 'Mã không hợp lệ hoặc đã hết hạn.\nVui lòng gửi lại mã.', err_server: 'Lỗi máy chủ. Vui lòng thử lại sau.', err_code: 'Vui lòng nhập đủ 6 chữ số' },
  mypage: { title: 'Trang của tôi', points: 'Điểm ssum', my_certs: 'Chứng chỉ của tôi', issue: 'Đăng ký tài sản', market: 'Chợ NFT', history: 'Lịch sử hoạt động', no_certs: 'Chưa có chứng chỉ nào', did: 'W3C DID' },
  issue: { title: 'Đăng ký SBT / NFT', step1: 'Loại tài sản', step2: 'Tải tệp lên', step3: 'Siêu dữ liệu', step4: 'Gửi', sbt_desc: 'Không thể chuyển nhượng — khóa bản sắc thương hiệu', nft_desc: 'Có thể chuyển nhượng — có thể niêm yết trên chợ', submit_btn: 'Gửi đến Atelier' },
  market: { title: 'Chợ NFT', filter_all: 'Tất cả', buy_btn: 'Mua bằng điểm', list_btn: 'Niêm yết trên chợ', price: 'Giá (Điểm)', seller: 'Người bán' },
  footer: { copy: '© 2026 award.bi · Powered by kei.bio · Ghi vĩnh viễn trên Bitcoin', links: { verify: 'Xác minh', api: 'Open API', brand: 'Thương hiệu', atelier: 'Atelier' } },
}
